meiduo_mall/meiduo_mall/apps/areas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^areas/$', views.AreaView.as_view()),
]

meiduo_mall/meiduo_mall/apps/carts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^carts/$', views.CartView.as_view()),
    url('^carts/selection/$', views.CartSelectView.as_view()),
    url('^carts/simple/$', views.CartSimpleView.as_view()),
]

meiduo_mall/meiduo_mall/apps/goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^list/(?P<category_id>\d+)/(?P<page_num>\d+)/$', views.ListView.as_view()),
    url('^hot/(?P<category_id>\d+)/$', views.HotView.as_view()),
    url('^detail/(?P<sku_id>\d+)/$', views.DetailView.as_view()),
    url('^detail/visit/(?P<category_id>\d+)/$', views.DetailVisitView.as_view()),
    url('^browse_histories/$', views.HistoryView.as_view()),
]

meiduo_mall/meiduo_mall/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('users.urls')),
    url('^', include('verifications.urls')),
    url('^', include('contents.urls')),
    url('^', include('oauth.urls')),
    url('^', include('areas.urls')),
    url('^', include('goods.urls')),
    url(r'^search/', include('haystack.urls')),
    url('^', include('carts.urls')),
    url('^', include('orders.urls')),
    url('^', include('payments.urls')),
]

meiduo_mall/meiduo_mall/apps/areas/models.py
from django.db import models


class Area(models.Model):
    # django自动创建名为id的主键，所以不需要定义
    # 地区名称
    name = models.CharField(max_length=30)
    # 父级地区对象，自关联
    parent = models.ForeignKey('self', null=True, related_name='subs')

    class Meta:
        db_table = 'tb_areas'

meiduo_mall/meiduo_mall/apps/carts/models.py
from django.db import models

# Create your models here.

meiduo_mall/meiduo_mall/apps/goods/models.py
from django.db import models
from meiduo_mall.utils.models import BaseModel


class GoodsCategory(BaseModel):
    """商品类别"""
    name = models.CharField(max_length=10, verbose_name='名称')
    parent = models.ForeignKey('self', related_name='subs', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='父类别')

    class Meta:
        db_table = 'tb_goods_category'
        verbose_name = '商品类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannelGroup(BaseModel):
    """商品频道组"""
    name = models.CharField(max_length=20, verbose_name='频道组名')

    class Meta:
        db_table = 'tb_channel_group'
        verbose_name = '商品频道组'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannel(BaseModel):
    """商品频道"""
    group = models.ForeignKey(GoodsChannelGroup, verbose_name='频道组名')
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='顶级商品类别')
    url = models.CharField(max_length=50, verbose_name='频道页面链接')
    sequence = models.IntegerField(verbose_name='组内顺序')

    class Meta:
        db_table = 'tb_goods_channel'
        verbose_name = '商品频道'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.category.name


class Brand(BaseModel):
    """品牌"""
    name = models.CharField(max_length=20, verbose_name='名称')
    logo = models.ImageField(verbose_name='Logo图片')
    first_letter = models.CharField(max_length=1, verbose_name='品牌首字母')

    class Meta:
        db_table = 'tb_brand'
        verbose_name = '品牌'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SPU(BaseModel):
    """商品SPU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, verbose_name='品牌')
    category1 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat1_spu', verbose_name='一级类别')
    category2 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat2_spu', verbose_name='二级类别')
    category3 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat3_spu', verbose_name='三级类别')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    desc_detail = models.TextField(default='', verbose_name='详细介绍')
    desc_pack = models.TextField(default='', verbose_name='包装信息')
    desc_service = models.TextField(default='', verbose_name='售后服务')

    class Meta:
        db_table = 'tb_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SKU(BaseModel):
    """商品SKU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    caption = models.CharField(max_length=100, verbose_name='副标题')
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, verbose_name='商品')
    category = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, verbose_name='从属类别')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='单价')
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='进价')
    market_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='市场价')
    stock = models.IntegerField(default=0, verbose_name='库存')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    is_launched = models.BooleanField(default=True, verbose_name='是否上架销售')
    default_image = models.ImageField(max_length=200, default='', null=True, blank=True, verbose_name='默认图片')

    class Meta:
        db_table = 'tb_sku'
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class SKUImage(BaseModel):
    """SKU图片"""
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE, verbose_name='sku')
    image = models.ImageField(verbose_name='图片')

    class Meta:
        db_table = 'tb_sku_image'
        verbose_name = 'SKU图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.id)


class SPUSpecification(BaseModel):
    """商品SPU规格"""
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, related_name='specs', verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='规格名称')

    class Meta:
        db_table = 'tb_spu_specification'
        verbose_name = '商品SPU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.spu.name, self.name)


class SpecificationOption(BaseModel):
    """规格选项"""
    spec = models.ForeignKey(SPUSpecification, related_name='options', on_delete=models.CASCADE, verbose_name='规格')
    value = models.CharField(max_length=20, verbose_name='选项值')

    class Meta:
        db_table = 'tb_specification_option'
        verbose_name = '规格选项'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.spec, self.value)


class SKUSpecification(BaseModel):
    """SKU具体规格"""
    sku = models.ForeignKey(SKU, related_name='specs', on_delete=models.CASCADE, verbose_name='sku')
    spec = models.ForeignKey(SPUSpecification, on_delete=models.PROTECT, verbose_name='规格名称')
    option = models.ForeignKey(SpecificationOption, on_delete=models.PROTECT, verbose_name='规格值')

    class Meta:
        db_table = 'tb_sku_specification'
        verbose_name = 'SKU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s - %s' % (self.sku, self.spec.name, self.option.value)

class GoodsVisitCount(BaseModel):
    """统计分类商品访问量模型类"""
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='商品分类')
    count = models.IntegerField(verbose_name='访问量', default=0)
    date = models.DateField(auto_now_add=True, verbose_name='统计日期')

    class Meta:
        db_table = 'tb_goods_visit'
        verbose_name = '统计分类商品访问量'
        verbose_name_plural = verbose_name

meiduo_mall/meiduo_mall/apps/oauth/models.py
from django.db import models
from users.models import User
from meiduo_mall.utils.models import BaseModel


class OAuthQQUser(BaseModel):
    # class OAuthQQUser(models.Model):
    user = models.ForeignKey(User)
    openid = models.CharField(max_length=50)

    class Meta:
        db_table = 'tb_oauth_qq'

meiduo_mall/meiduo_mall/apps/payments/models.py
from django.db import models
from meiduo_mall.utils.models import BaseModel
from orders.models import OrderInfo


class AlipayInfo(BaseModel):
    # 订单
    order = models.ForeignKey(OrderInfo, related_name='alipays')
    # 支付宝流水号
    alipay_id = models.CharField(max_length=100)

    class Meta:
        db_table = 'tb_alipay'

meiduo_mall/meiduo_mall/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from meiduo_mall.utils.models import BaseModel
from areas.models import Area


class User(AbstractUser):
    # 继承后，默认的属性、方法都有
    # 扩展新属性
    # 手机号
    mobile = models.CharField(max_length=11)
    # 邮箱激活状态
    email_active = models.BooleanField(default=False)
    # 默认收货地址
    default_address = models.ForeignKey('Address', related_name='users', null=True)

    class Meta:
        # 表名
        db_table = 'tb_users'


class Address(BaseModel):
    user = models.ForeignKey('User', related_name='addresses')  # 收货地址的用户
    title = models.CharField(max_length=10)  # 标题
    receiver = models.CharField(max_length=20)  # 收件人
    province = models.ForeignKey(Area, related_name='provinces')  # 省
    city = models.ForeignKey(Area, related_name='cities')  # 市
    district = models.ForeignKey(Area, related_name='districts')  # 区县
    detail = models.CharField(max_length=100)  # 详细地址
    mobile = models.CharField(max_length=11)  # 收件人的手机号
    tel = models.CharField(max_length=20, null=True)  # 固定电话，选填
    email = models.CharField(max_length=50, null=True)  # 邮箱，选填
    is_delete = models.BooleanField(default=False)  # 逻辑删除

    class Meta:
        db_table = 'tb_addresses'

    def to_dict(self):
        return {
            'id': self.id,
            'title': self.title,
            'receiver': self.receiver,
            'province_id': self.province_id,
            'province': self.province.name,
            'city_id': self.city_id,
            'city': self.city.name,
            'district_id': self.district_id,
            'district': self.district.name,
            'place': self.detail,
            'mobile': self.mobile,
            'tel': self.tel,
            'email': self.email
        }

meiduo_mall/meiduo_mall/apps/verifications/models.py
from django.db import models

# Create your models here.

meiduo_mall/meiduo_mall/apps/areas/views.py
from django.shortcuts import render
from django.views import View
from meiduo_mall.utils.response_code import RETCODE
from django import http
from .models import Area
from django.core.cache import cache
from . import contants


class AreaView(View):
    def get(self, request):
        # 接收
        area_id = request.GET.get('area_id')

        # 验证：area_id允许为空，表示查询省信息

        # 处理
        if area_id is None:
            # 读取缓存
            province_list = cache.get('province_list')

            if province_list is None:
                # 查询省信息
                provinces = Area.objects.filter(parent__isnull=True)
                # 转换字典
                province_list = []
                for province in provinces:
                    province_list.append({
                        'id': province.id,
                        'name': province.name
                    })

                # 写缓存
                cache.set('province_list', province_list, contants.AREA_CACHE_EXPIRES)

            # 响应
            return http.JsonResponse({
                'code': RETCODE.OK,
                'errmsg': 'ok',
                'province_list': province_list
            })
        else:
            # 读取缓存
            sub_data = cache.get('area_' + area_id)
            if sub_data is None:
                # 查询指定编号的地区及子级地区
                try:
                    area = Area.objects.get(pk=area_id)
                except:
                    return http.JsonResponse({
                        'code': RETCODE.PARAMERR,
                        'errmsg': '地区编号无效'
                    })
                else:
                    # 获取子级地区
                    subs = area.subs.all()
                    sub_list = []
                    for sub in subs:
                        sub_list.append({
                            'id': sub.id,
                            'name': sub.name
                        })
                    # 结果数据
                    sub_data = {
                        'id': area.id,
                        'name': area.name,
                        'subs': sub_list
                    }
                    # 写缓存
                    cache.set('area_' + area_id, sub_data, contants.AREA_CACHE_EXPIRES)

            return http.JsonResponse({
                'code': RETCODE.OK,
                'errmsg': 'ok',
                'sub_data': sub_data
            })
            # 响应

meiduo_mall/meiduo_mall/apps/contents/views.py
from django.shortcuts import render
from django.views import View
from goods.models import GoodsChannel, GoodsCategory
from meiduo_mall.utils.category import get_category
from .models import ContentCategory, Content


class IndexView(View):
    def get(self, request):
        # 频道分类信息
        categories = get_category()

        # 查询广告数据
        #1.查询广告位
        contents = ContentCategory.objects.all()
        content_dict = {}
        #2.遍历，查询每个位置的广告信息
        for content in contents:
            #3.将广告数据赋给指定的广告位
            content_dict[content.key] = content.content_set.filter(status=True).order_by('sequence')

        context = {
            'categories': categories,
            'contents': content_dict
        }
        return render(request, 'index.html', context)

meiduo_mall/meiduo_mall/apps/oauth/views.py
from django.shortcuts import render, redirect
from django.views import View
from django import http
from QQLoginTool.QQtool import OAuthQQ
from django.conf import settings

from carts.utils import merge_cart_cookie_to_redis
from meiduo_mall.utils.response_code import RETCODE
from .models import OAuthQQUser
from meiduo_mall.utils import meiduo_signature
from . import constants
from users.models import User
from django.contrib.auth import login


class QQurlView(View):
    def get(self, request):
        # 生成授权地址
        next_url = request.GET.get('next')
        # 1.创建工具对象
        qq_tool = OAuthQQ(
            settings.QQ_CLIENT_ID,
            settings.QQ_CLIENT_SECRET,
            settings.QQ_REDIRECT_URI,
            next_url
        )
        # 2.调用方法，生成url地址
        login_url = qq_tool.get_qq_url()

        # 响应
        return http.JsonResponse({
            'code': RETCODE.OK,
            'errmsg': 'ok',
            'login_url': login_url
        })


class QQopenidView(View):
    def get(self, request):
        # 获取openid
        # 1.接收code
        code = request.GET.get('code')
        next_url = request.GET.get('state')

        # 2.创建工具对象
        qq_tool = OAuthQQ(
            settings.QQ_CLIENT_ID,
            settings.QQ_CLIENT_SECRET,
            settings.QQ_REDIRECT_URI,
            next_url
        )

        try:
            # 3.根据code获取token
            token = qq_tool.get_access_token(code)

            # 4.根据token获取openid
            openid = qq_tool.get_open_id(token)

            # 绑定：与本网站的账号关联
            try:
                qquser = OAuthQQUser.objects.get(openid=openid)
            except:
                # 未找到绑定对象，说明是初次授权，展示绑定页面
                # 加密
                token = meiduo_signature.dumps({'openid': openid}, constants.OPENID_EXPIRES)
                # 展示页面
                context = {'token': token}
                return render(request, 'oauth_callback.html', context)
            else:
                # 查找到绑定对象，则状态保持
                login(request, qquser.user)
                response = redirect(next_url)
                response.set_cookie('username', qquser.user.username)

                # 合并购物车
                response = merge_cart_cookie_to_redis(request, response)

                return response

        except:
            openid = 0

        return http.HttpResponse(openid)

    def post(self, request):
        # 接收用户填写的数据，进行绑定
        # 接收
        token = request.POST.get('access_token')
        mobile = request.POST.get('mobile')
        pwd = request.POST.get('pwd')
        sms_code = request.POST.get('sms_code')

        next_url = request.GET.get('state')

        # 验证：非空，格式，短信验证码，与注册相同，不再重复
        # 解密openid
        json = meiduo_signature.loads(token, constants.OPENID_EXPIRES)
        if json is None:
            return http.HttpResponseBadRequest('授权信息已经过期')
        openid = json.get('openid')

        # 处理
        # 1.根据手机号查询用户对象
        try:
            user = User.objects.get(mobile=mobile)
        except:
            # 2.如果未查询到对象，则新建用户对象
            user = User.objects.create_user(username=mobile, password=pwd, mobile=mobile)
        else:
            # 3.如果查询到用户对象，则判断密码
            if not user.check_password(pwd):
                # 3.1如果密码错误，则提示
                return http.HttpResponseBadRequest('账号信息无效')
                # 3.2如果密码正确则得到用户对象

        # 4.绑定：创建OAuthQQUser对象
        OAuthQQUser.objects.create(user=user, openid=openid)

        # 5.状态保持
        login(request, user)
        response = redirect(next_url)
        response.set_cookie('username', user.username, max_age=60 * 60 * 24 * 14)

        # 合并购物车
        response = merge_cart_cookie_to_redis(request, response)

        # 响应
        return response

meiduo_mall/meiduo_mall/templates/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>美多商城-购物车</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/host.js"></script>
	<script type="text/javascript" src="/static/js/vue-2.5.16.js"></script>
    <script type="text/javascript" src="/static/js/axios-0.18.0.min.js"></script>
</head>
<body>
	<div id="app" v-cloak>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到美多商城!</div>
			<div class="fr">
            <div class="fr">
                <div class="login_btn fl" v-if="username">
                    欢迎您：<em>[[ username ]]</em>
                    <span>|</span>
                    <a href="/logout/" class="quit">退出</a>
                </div>
                <div class="login_btn fl" v-else>
                    <a href="/login/">登录</a>
                    <span>|</span>
                    <a href="/register/">注册</a>
                </div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="/static/user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_wrap fl">
			<form method="get" action="/search/" class="search_con">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
			<ul class="search_suggest fl">
				<li><a href="#">索尼微单</a></li>
				<li><a href="#">优惠15元</a></li>
				<li><a href="#">美妆个护</a></li>
				<li><a href="#">买2免1</a></li>
			</ul>
		</div>
	</div>

	<div class="total_count">全部商品<em>[[total_count]]</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

	<ul class="cart_list_td clearfix" v-for="(sku,index) in carts">
		<li class="col01"><input type="checkbox" name="selected" v-model="sku.selected" @change="update_selected(index)"></li>
		<li class="col02"><img :src="sku.default_image_url"></li>
		<li class="col03">[[sku.name]]</li>
		<li class="col04">台</li>
		<li class="col05">[[sku.price]]元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl" @click="on_add(index)">+</a>
				<input type="text" class="num_show fl" v-model="sku.count" autocomplete="off" @blur="on_input(index)">
				<a href="javascript:;" class="minus fl" @click="on_minus(index)">-</a>
			</div>
		</li>
		<li class="col07">[[sku.total_amount]]元</li>
		<li class="col08"><a href="javascript:;" @click="on_delete(index)">删除</a></li>
	</ul>

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="selected_all" :checked="selected_all" @change="on_selected_all"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>[[total_selected_amount]]</em><br>共计<b>[[total_selected_count]]</b>件商品</li>
		<li class="col04"><a href="/orders/settlement/">去结算</a></li>
	</ul>
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	</div>
	<script>
        var cart_skus = {{ cart_skus|safe }};
    </script>
    <script type="text/javascript" src="/static/js/common.js"></script>
	<script type="text/javascript" src="/static/js/cart.js"></script>
</body>
</html>

meiduo_mall/meiduo_mall/templates/place_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>美多商城-订单确认</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/host.js"></script>
    <script type="text/javascript" src="/static/js/vue-2.5.16.js"></script>
    <script type="text/javascript" src="/static/js/axios-0.18.0.min.js"></script>
</head>
<body>
<div id="app" v-cloak>
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到美多商城!</div>
            <div class="fr">
                <div class="login_info fl">
                    欢迎您：<em>张 山</em>
                </div>
                <div class="login_btn fl">
                    <a href="login.html">登录</a>
                    <span>|</span>
                    <a href="../templates/register.html">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="user_center_info.html">用户中心</a>
                    <span>|</span>
                    <a href="cart.html">我的购物车</a>
                    <span>|</span>
                    <a href="user_center_order.html">我的订单</a>
                </div>
            </div>
        </div>
    </div>

    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="search_wrap fl">
            <form method="get" action="/search/" class="search_con">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
            <ul class="search_suggest fl">
                <li><a href="#">索尼微单</a></li>
                <li><a href="#">优惠15元</a></li>
                <li><a href="#">美妆个护</a></li>
                <li><a href="#">买2免1</a></li>
            </ul>
        </div>
    </div>

    <h3 class="common_title">确认收货地址</h3>

    <div class="common_list_con clearfix" id="get_site">
        <dl>
            <dt>寄送到：</dt>
            {% for address in address_list %}
                <dd>
                    <input type="radio" name="address_id" value="{{ address.id }}" @click="nowsite={{ address.id }}"
                            {% if default_address_id == address.id %} checked="checked"{% endif %}
                    />
                    {{ address.province.name }} {{ address.city.name }} {{ address.district.name }} {{ address.detail }}
                    （{{ address.receiver }} 收）{{ address.mobile }}
                </dd>
            {% endfor %}
        </dl>
        <a href="user_center_site.html" class="edit_site">编辑收货地址</a>
    </div>

    <h3 class="common_title">支付方式</h3>
    <div class="common_list_con clearfix">
        <div class="pay_style_con clearfix">
            <input type="radio" name="pay_method" value="1" @click="pay_method=1">
            <label class="cash">货到付款</label>
            <input type="radio" name="pay_method" value="2" checked="checked" @click="pay_method=2">
            <label class="zhifubao"></label>
        </div>
    </div>

    <h3 class="common_title">商品列表</h3>

    <div class="common_list_con clearfix">
        <ul class="goods_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
        </ul>
        {% for sku in sku_list %}
            <ul class="goods_list_td clearfix">
                <li class="col01">{{ sku.id }}</li>
                <li class="col02"><img src="{{ sku.default_image_url }}"></li>
                <li class="col03">{{ sku.name }}</li>
                <li class="col04">台</li>
                <li class="col05">{{ sku.price }}元</li>
                <li class="col06">{{ sku.count }}</li>
                <li class="col07">{{ sku.total_amount }}元</li>
            </ul>
        {% endfor %}

    </div>

    <h3 class="common_title">总金额结算</h3>

    <div class="common_list_con clearfix">
        <div class="settle_con">
            <div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_money }}元</b></div>
            <div class="transit">运费：<b>{{ freight }}元</b></div>
            <div class="total_pay">实付款：<b>{{ pay_money }}元</b></div>
        </div>
    </div>

    <div class="order_submit clearfix">
        <a href="javascript:;" id="order_btn" @click="on_order_submit">提交订单</a>

    </div>

    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
</div>
<script type="text/javascript">
    let payment_amount ={{ pay_money }};
    let default_address_id ={{ default_address_id }};
</script>
<script type="text/javascript" src="/static/js/common.js"></script>
<script type="text/javascript" src="/static/js/place_order.js"></script>
</body>
</html>